### ISSUE TITLE
unable to enable native messaging in KeePassXC

### ISSUE THREAD

**Issue by dancju** [City-busz/Arch-Linux-Repository#4]
Please build KeePassXC with `-DWITH_XC_BROWSER=ON` in Arch Linux Community Repository.

https://github.com/varjolintu/keepassxc/issues/8#issuecomment-334358452

**Comment by City-busz** [comment]
This option is an experimental feature, and not available in the latest stable release, so I can't enable it. Please use the [Arch Linux Bugtracker](https://bugs.archlinux.org/) next time.
